"""empty message

Revision ID: 7d56cfa69c80
Revises: 
Create Date: 2020-09-25 17:18:22.266254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d56cfa69c80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index('ix_products_index', table_name='products')
    op.drop_column('products', 'index')
    op.add_column('reviews', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index('ix_reviews_index', table_name='reviews')
    op.create_foreign_key(None, 'reviews', 'products', ['asin'], ['asin'])
    op.drop_column('reviews', 'index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_index('ix_reviews_index', 'reviews', ['index'], unique=False)
    op.drop_column('reviews', 'id')
    op.add_column('products', sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_index('ix_products_index', 'products', ['index'], unique=False)
    op.drop_column('products', 'id')
    # ### end Alembic commands ###
